xfce4-dev-tools
libxfce4util
xfconf
libxfce4ui
exo
garcon
xfce4-panel
thunar
thunar-volman
tumbler
xfce4-appfinder
xfce4-power-manager
xfce4-settings
xfdesktop
xfwm4
xfce4-session
xfce4-notifyd
xfce4-taskmanager
xfce4-screenshooter
orage
vte2
xfce4-terminal
xfce4-clipman-plugin
xfce4-systemload-plugin
xfce4-weather-plugin
xfce4-xkb-plugin
xfce4-sensors-plugin
xfce4-cpufreq-plugin
xfce4-places-plugin
thunar-archive-plugin
xfce4-whiskermenu-plugin
libunique
xfce4-notes-plugin
gstreamer0
gst0-plugins-base
gst0-plugins-good
xfce4-mixer
xfwm4-themes
gtk-xfce-engine
gnome-icon-theme
